[package]
name = "instant"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4", features = ["derive"] }
colored = "3.0.0"
directories = "6.0.0"
indicatif = "0.18.0"
owo-colors = "4.2.2"
rusqlite = "0.37.0"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.9.5"
walkdir = "2.5.0"
