//! Compile the assist registry into window-manager mode configurations.
//!
//! The assist tree is compiled once into a backend-neutral mode graph. Format
//! renderers are intentionally small so Sway/i3 and instantWM share navigation,
//! help, key hints, and leaf-exit semantics.

use std::fmt::Write;

use anyhow::Result;

use super::registry::{ASSISTS, AssistEntry};

const ROOT_MODE: &str = "instantassist";

#[derive(Debug, Clone, PartialEq, Eq)]
enum ModeBinding {
    Action {
        key: char,
        key_sequence: String,
    },
    Group {
        key: char,
        target_name: String,
        target_display: String,
    },
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct AssistMode {
    name: String,
    display: String,
    prefix: String,
    bindings: Vec<ModeBinding>,
    children: Vec<AssistMode>,
}

impl AssistMode {
    fn compile_root(entries: &[AssistEntry]) -> Self {
        Self::compile(entries, ROOT_MODE, "", "instantassist")
    }

    fn compile(entries: &[AssistEntry], name: &str, prefix: &str, description: &str) -> Self {
        let mut children = Vec::new();

        for entry in entries {
            if let AssistEntry::Group(group) = entry {
                let target_name = format!("{name}_{}", group.key);
                let target_prefix = format!("{prefix}{}", group.key);
                children.push(Self::compile(
                    group.children,
                    &target_name,
                    &target_prefix,
                    group.description,
                ));
            }
        }

        let bindings = entries
            .iter()
            .filter_map(|entry| match entry {
                // In submodes, `h` is reserved for contextual help.
                AssistEntry::Action(action) if !prefix.is_empty() && action.key == 'h' => None,
                AssistEntry::Action(action) => Some(ModeBinding::Action {
                    key: action.key,
                    key_sequence: format!("{prefix}{}", action.key),
                }),
                AssistEntry::Group(group) => {
                    let child = children
                        .iter()
                        .find(|child| child.name == format!("{name}_{}", group.key))
                        .expect("compiled assist group must have a child mode");
                    Some(ModeBinding::Group {
                        key: group.key,
                        target_name: child.name.clone(),
                        target_display: child.display.clone(),
                    })
                }
            })
            .collect::<Vec<_>>();

        let mut keys = bindings
            .iter()
            .map(|binding| match binding {
                ModeBinding::Action { key, .. } | ModeBinding::Group { key, .. } => *key,
            })
            .collect::<Vec<_>>();
        keys.sort_unstable();
        let key_hint = keys
            .iter()
            .map(char::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        let display = if key_hint.is_empty() {
            format!("{description} (h for help)")
        } else {
            format!("{description} (keys: {key_hint}) (h for help)")
        };

        Self {
            name: name.to_string(),
            display,
            prefix: prefix.to_string(),
            bindings,
            children,
        }
    }
}

/// Render the canonical Sway/i3 assist integration.
pub(crate) fn render_sway_like(wm_name: &str) -> Result<String> {
    let root = AssistMode::compile_root(ASSISTS);
    let mut output = String::new();

    writeln!(output, "# {wm_name} config for instantCLI assists")?;
    writeln!(
        output,
        "# Generated by instantCLI. Manual edits may be overwritten."
    )?;
    writeln!(output)?;
    writeln!(output, "bindsym $mod+a mode {}", sway_quote(&root.display))?;
    writeln!(output)?;
    render_sway_mode(&mut output, &root)?;
    writeln!(output, "# End of instantCLI assists config")?;

    Ok(output)
}

fn render_sway_mode(output: &mut String, mode: &AssistMode) -> Result<()> {
    writeln!(output, "mode {} {{", sway_quote(&mode.display))?;
    writeln!(output, "    bindsym Return mode default")?;
    writeln!(output, "    bindsym Escape mode default")?;

    if !mode.prefix.is_empty() {
        writeln!(
            output,
            "    bindsym h mode default; exec --no-startup-id ins assist run {}h",
            mode.prefix
        )?;
    }

    for binding in &mode.bindings {
        match binding {
            ModeBinding::Action { key, key_sequence } => writeln!(
                output,
                "    bindsym {key} mode default; exec --no-startup-id ins assist run {key_sequence}"
            )?,
            ModeBinding::Group {
                key,
                target_display,
                ..
            } => writeln!(
                output,
                "    bindsym {key} mode {}",
                sway_quote(target_display)
            )?,
        }
    }

    writeln!(output, "}}")?;
    writeln!(output)?;

    for child in &mode.children {
        render_sway_mode(output, child)?;
    }

    Ok(())
}

/// Render the canonical instantWM assist integration.
pub(crate) fn render_instantwm() -> Result<String> {
    let root = AssistMode::compile_root(ASSISTS);
    let mut output = String::new();

    writeln!(output, "# instantWM config for instantCLI assists")?;
    writeln!(
        output,
        "# Generated by instantCLI. Manual edits may be overwritten."
    )?;
    writeln!(output)?;
    writeln!(output, "[[keybinds]]")?;
    writeln!(output, "modifiers = [\"Super\"]")?;
    writeln!(output, "key = \"a\"")?;
    writeln!(output, "action = {{ set_mode = \"{}\" }}", root.name)?;
    writeln!(output)?;
    render_instantwm_mode(&mut output, &root)?;
    writeln!(output, "# End of instantCLI assists config")?;

    Ok(output)
}

fn render_instantwm_mode(output: &mut String, mode: &AssistMode) -> Result<()> {
    writeln!(output, "[modes.{}]", mode.name)?;
    writeln!(output, "description = {}", toml_string(&mode.display))?;
    writeln!(output, "keybinds = [")?;
    writeln!(
        output,
        "  {{ modifiers = [], key = \"Escape\", action = {{ set_mode = \"default\" }} }},"
    )?;
    writeln!(
        output,
        "  {{ modifiers = [], key = \"Return\", action = {{ set_mode = \"default\" }} }},"
    )?;

    if !mode.prefix.is_empty() {
        write_instantwm_leaf(output, 'h', &format!("{}h", mode.prefix))?;
    }

    for binding in &mode.bindings {
        match binding {
            ModeBinding::Action { key, key_sequence } => {
                write_instantwm_leaf(output, *key, key_sequence)?;
            }
            ModeBinding::Group {
                key, target_name, ..
            } => writeln!(
                output,
                "  {{ modifiers = [], key = \"{key}\", action = {{ set_mode = \"{target_name}\" }} }},"
            )?,
        }
    }

    writeln!(output, "]")?;
    writeln!(output)?;

    for child in &mode.children {
        render_instantwm_mode(output, child)?;
    }

    Ok(())
}

fn write_instantwm_leaf(output: &mut String, key: char, key_sequence: &str) -> Result<()> {
    writeln!(
        output,
        "  {{ modifiers = [], key = \"{key}\", action = {{ sequence = [{{ set_mode = \"default\" }}, {{ spawn = [\"ins\", \"assist\", \"run\", \"{key_sequence}\"] }}] }} }},"
    )?;
    Ok(())
}

fn sway_quote(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn toml_string(value: &str) -> String {
    toml::Value::String(value.to_string()).to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::assist::registry::{AssistAction, AssistGroup};
    use crate::ui::prelude::NerdFont;

    fn noop() -> anyhow::Result<()> {
        Ok(())
    }

    static NESTED_LEAF: &[AssistEntry] = &[AssistEntry::Action(AssistAction {
        key: 'z',
        description: "Nested leaf",
        icon: NerdFont::Question,
        dependencies: &[],
        execute: noop,
    })];
    static NESTED_GROUP: &[AssistEntry] = &[AssistEntry::Group(AssistGroup {
        key: 'y',
        description: "Nested group",
        icon: NerdFont::Question,
        children: NESTED_LEAF,
    })];
    static NESTED_ROOT: &[AssistEntry] = &[AssistEntry::Group(AssistGroup {
        key: 'x',
        description: "Root group",
        icon: NerdFont::Question,
        children: NESTED_GROUP,
    })];

    #[test]
    fn semantic_graph_supports_arbitrary_nesting_and_group_descriptions() {
        let root = AssistMode::compile_root(NESTED_ROOT);
        assert_eq!(root.children[0].name, "instantassist_x");
        assert!(root.children[0].display.starts_with("Root group"));
        assert_eq!(root.children[0].children[0].name, "instantassist_x_y");
        assert!(
            root.children[0].children[0]
                .display
                .starts_with("Nested group")
        );
        assert!(matches!(
            &root.children[0].children[0].bindings[0],
            ModeBinding::Action { key_sequence, .. } if key_sequence == "xyz"
        ));
    }

    #[test]
    fn instantwm_config_installs_entry_binding_and_exits_before_leaf_spawn() {
        let output = render_instantwm().unwrap();
        assert!(output.contains(
            "action = { sequence = [{ set_mode = \"default\" }, { spawn = [\"ins\", \"assist\", \"run\", \"sf\"] }] }"
        ));
        assert!(output.contains(
            "[[keybinds]]\nmodifiers = [\"Super\"]\nkey = \"a\"\naction = { set_mode = \"instantassist\" }"
        ));
    }

    #[test]
    fn instantwm_descriptions_use_groups_and_key_hints() {
        let output = render_instantwm().unwrap();
        assert!(
            output.contains("description = \"Screenshot: Screenshot and annotation tools (keys:")
        );
        assert!(
            !output.contains(
                "Fullscreen to Pictures: Fullscreen screenshot to Pictures folder submode"
            )
        );
    }

    #[test]
    fn generated_instantwm_config_is_valid_toml() {
        let output = render_instantwm().unwrap();
        toml::from_str::<toml::Value>(&output).unwrap();
    }

    #[test]
    fn sway_and_instantwm_share_leaf_and_group_semantics() {
        let sway = render_sway_like("Sway").unwrap();
        let instantwm = render_instantwm().unwrap();

        assert!(sway.contains("bindsym s mode \"Screenshot: Screenshot and annotation tools"));
        assert!(instantwm.contains("key = \"s\", action = { set_mode = \"instantassist_s\" }"));
        assert!(sway.contains("bindsym f mode default; exec --no-startup-id ins assist run sf"));
        assert!(instantwm.contains(
            "key = \"f\", action = { sequence = [{ set_mode = \"default\" }, { spawn = [\"ins\", \"assist\", \"run\", \"sf\"] }] }"
        ));
    }
}
