#!/bin/sh

set -eu

SCRIPT_DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
SOURCE_DIR="$SCRIPT_DIR/install-src"
ENTRYPOINT="$SOURCE_DIR/install.sh"
OUTPUT="$SCRIPT_DIR/install.sh"
CHECK_ONLY=0
INCLUDE_STACK=""

usage() {
	cat <<EOF
Usage: build-install.sh [--check]

Build the modular installer sources into scripts/install.sh.

Options:
  --check  Verify that the committed generated installer is current
  -h       Show this help message
EOF
}

while [ $# -gt 0 ]; do
	case "$1" in
	--check)
		CHECK_ONLY=1
		;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		printf 'error: unknown argument: %s\n' "$1" >&2
		usage >&2
		exit 1
		;;
	esac
	shift
done

bundle_file() (
	file=$1
	relative_file=${file#"$SOURCE_DIR"/}

	case ":$INCLUDE_STACK:" in
	*:"$relative_file":*)
		printf 'error: circular installer include: %s\n' "$relative_file" >&2
		exit 1
		;;
	esac

	INCLUDE_STACK=${INCLUDE_STACK:+$INCLUDE_STACK:}$relative_file

	while IFS= read -r line || [ -n "$line" ]; do
		case "$line" in
		'# @include '*)
			include=${line#\# @include }
			case "$include" in
			"" | /*)
				printf 'error: invalid installer include in %s: %s\n' "$relative_file" "$include" >&2
				exit 1
				;;
			esac
			case "/$include/" in
			*/../*)
				printf 'error: invalid installer include in %s: %s\n' "$relative_file" "$include" >&2
				exit 1
				;;
			esac

			include_path="$SOURCE_DIR/$include"
			if [ ! -f "$include_path" ]; then
				printf 'error: installer include not found: %s\n' "$include" >&2
				exit 1
			fi
			bundle_file "$include_path"
			;;
		*)
			printf '%s\n' "$line"
			;;
		esac
	done <"$file"

)

temp_output=$(mktemp "$SCRIPT_DIR/.install.sh.XXXXXX")
cleanup() {
	rm -f "$temp_output"
}
trap cleanup EXIT HUP INT TERM

{
	printf '#!/bin/sh\n\n'
	printf '# Code generated by scripts/build-install.sh; DO NOT EDIT.\n'
	printf '# Edit scripts/install-src/*.sh and rebuild instead.\n\n'
	printf 'set -eu\n\n'
	bundle_file "$ENTRYPOINT"
} >"$temp_output"

chmod 755 "$temp_output"

if [ "$CHECK_ONLY" -eq 1 ]; then
	if ! cmp -s "$temp_output" "$OUTPUT"; then
		printf 'error: %s is out of date; run scripts/build-install.sh\n' "$OUTPUT" >&2
		if command -v diff >/dev/null 2>&1; then
			diff -u "$OUTPUT" "$temp_output" || true
		fi
		exit 1
	fi
	exit 0
fi

mv "$temp_output" "$OUTPUT"
trap - EXIT HUP INT TERM
