pub mod audio_preprocessing;
pub mod check;
pub mod cli;
pub mod commands;
mod config;
mod convert;
mod document;
mod ffmpeg;
mod markdown;
mod markdown_utils;
mod music;
pub mod planner;
pub mod render;
mod render_timeline;
pub mod setup;
mod slide;
pub mod stats;
mod transcribe;
pub mod transcript;
mod utils;

pub use cli::VideoCommands;
pub use commands::handle_video_command;
